apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pine
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: yefriddavid/kube-api-go:v1
          ports:
            - name: pine-service
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pine-service
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8080
      nodePort: 30091
  type: NodePort

